spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://virement-service
            predicates:
              - Path=/api/virements/**
          - id: r2
            uri: lb://benificiaire-service
            predicates:
              - Path=/api/benificiaires/**

server:
  port: 80
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8762/eureka/